[profile.default]
solc-version = "0.8.18"
optimizer = true
optimizer-runs = 200
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
gas_reports = ["*"]

[fuzz]
runs = 60000